# Generated by Django 4.1.7 on 2023-02-20 22:02

import activitiesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('act_trk_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_main_id', models.IntegerField(verbose_name=activitiesapp.models.Activity)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_tracker',
                'managed': True,
            },
        ),
    ]
